# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues

newIssueWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸš€âš¡
  
  
  Thank you and congratsğŸ‰ for opening your very first issue in this project. ToDoista is a web application made with MongoDB, Express.js, React.js and Node.js. It has a simple motive to fulfil- making todo lists simple.
  Please adhere to our [Code of Conduct](https://github.com/garimasingh128/ToDoista/blob/develop/CODE_OF_CONDUCT.md).ğŸ™Œ
  You may submit a PR if you like, make sure to follow our [Pull Request Template](https://github.com/garimasingh128/ToDoista/blob/develop/.github/PULL_REQUEST_TEMPLATE.md).
  If you want to report a bugğŸ please follow our [Issue Template](https://github.com/garimasingh128/ToDoista/tree/develop/.github/ISSUE_TEMPLATE). Also make sure you include steps to reproduce it and be patient while we get back to you.ğŸ˜„
  
  
  Feel free to join our [Gitter Channel](https://gitter.im/NWoC2020/ToDoista).ğŸ’– We have an active community overthere.âœ¨ Hope you have a great time there!ğŸ˜„
  
  
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸ’–
  
  
  Thank you and congratsğŸ‰ for opening your first pull request.âœ¨ ToDoista is a web application made with MongoDB, Express.js, React.js and Node.js. It has a simple motive to fulfil- making todo lists simple.
  Please adhere to our [Code of Conduct](https://github.com/garimasingh128/ToDoista/blob/develop/CODE_OF_CONDUCT.md).ğŸ™Œ We will get back to you as soon as we can ğŸ˜„.
  
  Feel free to join our [Gitter Channel](https://gitter.im/NWoC2020/ToDoista).ğŸ’– We have an active community overthere.âœ¨ Hope you have a great time there!ğŸ˜„
  
  
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ All the best for your amazing open source journey ahead .ğŸš€